version: 2
updates:
  # GitHub Actionsの依存関係を監視
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 10

  # Rubyの依存関係（Gemfile）を監視
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 10