name: Daily Report Update with Jules

on:
  schedule:
    # 毎日日本時間 18:00 (UTC 09:00) に実行
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能

permissions:
  contents: read

jobs:
  update-oldest-report:
    name: Update oldest report using Jules API
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: Find oldest report and call Jules API with retry
        uses: actions/github-script@v8
        env:
          JULES_API_KEY: ${{ secrets.JULES_API_KEY }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // _reportsディレクトリ内のすべてのMarkdownファイルを取得
            const reportsDir = '_reports';
            const files = fs.readdirSync(reportsDir).filter(file => file.endsWith('.md'));

            if (files.length === 0) {
              core.info('No report files found in _reports directory');
              return;
            }

            let oldestReport = null;
            let oldestDate = new Date();

            // 各レポートファイルのlast_updatedを確認
            for (const file of files) {
              const filePath = path.join(reportsDir, file);
              const content = fs.readFileSync(filePath, 'utf8');

              // YAMLフロントマターからlast_updatedを抽出
              const frontMatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
              if (frontMatterMatch) {
                const frontMatter = frontMatterMatch[1];
                const lastUpdatedMatch = frontMatter.match(/last_updated:\s*["']?([^"'\r\n]+)["']?/);

                if (lastUpdatedMatch) {
                  const lastUpdated = new Date(lastUpdatedMatch[1]);
                  core.info(`${file}: last_updated = ${lastUpdated.toISOString()}`);

                  if (lastUpdated < oldestDate) {
                    oldestDate = lastUpdated;
                    oldestReport = {
                      filename: file,
                      path: filePath,
                      lastUpdated: lastUpdated,
                      content: content
                    };
                  }
                }
              }
            }

            if (!oldestReport) {
              core.error('No report with valid last_updated date found');
              process.exit(1);
            }

            core.info(`Oldest report: ${oldestReport.filename} (last updated: ${oldestReport.lastUpdated.toISOString()})`);

            // ツール名を抽出
            const toolNameMatch = oldestReport.content.match(/tool_name:\s*["']?([^"'\r\n]+)["']?/);
            const toolName = toolNameMatch ? toolNameMatch[1] : oldestReport.filename.replace('.md', '');

            // Jules API用のプロンプトを作成
            const prompt = `task-report-create-or-update.mdに従い、${toolName}(${oldestReport.path})の調査レポートを最新情報に更新して。`;

            // Jules APIを呼び出し
            const julesApiUrl = 'https://jules.googleapis.com/v1alpha/sessions';
            const apiKey = process.env.JULES_API_KEY;

            if (!apiKey) {
              core.error('JULES_API_KEY secret is not set');
              process.exit(1);
            }

            const requestBody = {
              prompt: prompt,
              sourceContext: {
                source: `sources/github/${context.repo.owner}/${context.repo.repo}`,
                githubRepoContext: {
                  startingBranch: "main"
                }
              },
              requirePlanApproval: false,
              automationMode: `AUTO_CREATE_PR`,
              title: `Update ${toolName} Report - ${new Date().toISOString().split('T')[0]}`
            };

            // リトライ機能付きのJules API呼び出し
            const maxRetries = 3;
            const retryDelay = 30000; // 30秒
            let lastError = null;

            for (let attempt = 1; attempt <= maxRetries; attempt++) {
              core.info(`Jules API call attempt ${attempt}/${maxRetries}...`);
              
              if (attempt > 1) {
                core.info(`Waiting ${retryDelay/1000} seconds before retry...`);
                await new Promise(resolve => setTimeout(resolve, retryDelay));
              }

              try {
                const response = await fetch(julesApiUrl, {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    'X-Goog-Api-Key': apiKey
                  },
                  body: JSON.stringify(requestBody)
                });

                if (!response.ok) {
                  const errorText = await response.text();
                  const errorMessage = `Jules API call failed: ${response.status} ${response.statusText}`;
                  core.error(errorMessage);
                  core.error(`Error response: ${errorText}`);
                  
                  lastError = new Error(`${errorMessage}\nResponse: ${errorText}`);
                  
                  // 5xx系エラーの場合はリトライ、4xx系エラーの場合は即座に失敗
                  if (response.status >= 400 && response.status < 500) {
                    core.error('Client error (4xx) detected. Not retrying.');
                    throw lastError;
                  }
                  
                  if (attempt === maxRetries) {
                    throw lastError;
                  }
                  
                  core.warning(`Server error (5xx) detected. Will retry (${attempt}/${maxRetries})`);
                  continue;
                }

                const result = await response.json();
                core.info('Jules API call successful!');
                core.info(`Response: ${JSON.stringify(result, null, 2)}`);

                // 成功をGitHub Actionsの出力として設定
                core.setOutput('updated_report', oldestReport.filename);
                core.setOutput('tool_name', toolName);
                core.setOutput('jules_session_id', result.sessionId || 'unknown');
                
                return; // 成功したので関数を終了

              } catch (error) {
                lastError = error;
                core.error(`Error calling Jules API (attempt ${attempt}): ${error.message}`);
                
                if (attempt === maxRetries) {
                  core.error(`All ${maxRetries} attempts failed. Failing the workflow.`);
                  throw error;
                }
                
                core.warning(`Will retry (${attempt}/${maxRetries})`);
              }
            }
